feature: add styles for one-click-order button
abak-press/apress-ui pull request #179
Opened 2020-09-22 11:40 UTC by endiko

[MINOR]: Добавит новые стили для кнопки Заказать в 1 клик

https://jira.railsc.ru/browse/PC4-25724

2020-09-22 11:40 UTC, endiko commented
@Saymell => @ levushkina => @ idbolshakov

2020-09-22 11:43 UTC, Saymell approved these changes
@levushkina

2020-09-22 14:43 UTC, idbolshakov requested changes

2020-09-22 14:43 UTC, idbolshakov commented on src/blocks/pulscen/button/button_one-click.css
> +.aui-button_one-click {
классы с перфиксом `aui` должны быть описаны  в библиотеке компонетов  https://github.com/abak-press/apress-ui и только там

2020-09-22 15:02 UTC, levushkina commented on src/blocks/pulscen/button/button_one-click.css
> +.aui-button_one-click {
это ж она и есть

2020-09-22 15:39 UTC, idbolshakov commented on src/blocks/pulscen/button/button_one-click.css
> +.aui-button_one-click {
переклинило, я думал это пц репозиторий))

2020-09-22 15:40 UTC, idbolshakov commented on src/blocks/pulscen/button/button_one-click.css
> +.aui-button_one-click {
а все Маринины замечания актуальны

2020-09-23 06:57 UTC, endiko commented
тогда закрываю ПР

2020-09-23 06:57 UTC, closed without merging