feature(buttons): create new BEM-modifier
abak-press/apress-ui pull request #204
Opened 2021-04-23 08:50 UTC by FonDumik

[MINOR] Добавит новый БЭМ-модификатор "dark" для кнопки aui-button
https://jira.railsc.ru/browse/SG-7104

2021-04-23 09:44 UTC, FonDumik commented
@idbolshakov

2021-04-23 13:47 UTC, idbolshakov requested changes
эта кнопка не нужна нигде кроме лукмарта, не нужно создавать модификатор  dark в общем скоупе. Нужно только в лукмарте

2021-04-26 04:17 UTC, FonDumik commented
@idbolshakov 
@VeraVLVlas

2021-04-26 07:45 UTC, VeraVLVlas commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
Укажи type кнопки

2021-04-26 07:45 UTC, VeraVLVlas commented on src/blocks/lookmart/button/button_dark.css
> +.aui-button_dark:active { background: #000; }
Для лучшей читаемости кода можно написать так 
.aui-button_dark { 
  background: #000; 
} и.т.д

2021-04-26 07:55 UTC, VeraVLVlas commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
dark - это модификатор, модификатор по БЭМ это сущность, определяющая внешний вид, состояние или поведение блока либо элемента, как в твоем случае это цвет, поэтому правильно будет прописать 
aui-button--dark
Можно повторить материал здесь 
https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

2021-04-26 07:58 UTC, FonDumik commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
> Укажи type кнопки

насколько я помню, type указывается в случаях, когда используем input, разве нет?

2021-04-26 08:00 UTC, VeraVLVlas commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
dark в твоем случае это модификатор, модификатор по БЭМ  - это сущность, определяющая внешний вид, состояние или поведение блока либо элемента. Поэтому правильно прописать aui-button--dark
Ссылка для закрепления) 
https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

2021-04-26 08:04 UTC, VeraVLVlas commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
> > Укажи тип кнопки
> 
> насколько я помню, тип указывается в случаях, когда используется ввод, разве нет?



Для большинства браузеров значение typeпо умолчанию button- submit, поэтому лучше указывать явно

2021-04-26 08:13 UTC, FonDumik commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
> dark в твоем случае это модификатор, модификатор по БЭМ - это сущность, определяющая внешний вид, состояние или поведение блока либо элемента. Поэтому правильно прописать aui-button--dark
> Ссылка для закрепления)
> https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

по принципам того же БЭМа модификатор может указываться как "элемент_модификатор", так и "элемент--модификатор". В Абаке принято именовать БЭМ-блоки по первому варианту,  [для примера](https://github.com/abak-press/apress-ui/tree/master/src/blocks/common/button)

2021-04-26 09:33 UTC, FonDumik commented on src/blocks/lookmart/button/example/dark.html
> +<button class="aui-button aui-button_dark">Написать</button>
Указал type

2021-04-26 09:35 UTC, FonDumik commented
@idbolshakov

2021-04-26 18:34 UTC, idbolshakov requested changes

2021-04-26 18:34 UTC, idbolshakov commented on src/blocks/lookmart/button/notes/dark.json
> +  "extends": "common/button/notes/common.json"
а что тут просто extends'ом получится обойтись? Текст тоже нужен ведь?

2021-04-26 18:34 UTC, idbolshakov commented
и ребейз

2021-04-27 03:01 UTC, FonDumik commented on src/blocks/lookmart/button/notes/dark.json
> +  "extends": "common/button/notes/common.json"
> а что тут просто extends'ом получится обойтись? Текст тоже нужен ведь?

Текст подтягивается из common.json как "Стандартная кнопка с заливкой". Я не уверен, что это действительно нужно, так как у некоторых кнопок описание отсутствует

2021-04-27 04:45 UTC, closed without merging

2021-04-27 07:26 UTC, idbolshakov commented
если закрываешь ПР то указывай ссылку на новый ПР

https://github.com/abak-press/apress-ui/pull/207