[WIP] feat: add admin layout goods edit classes
abak-press/apress-ui pull request #221
Opened 2021-06-07 12:53 UTC by CillianFrost

https://jira.railsc.ru/browse/GOODS-2850

2021-06-07 17:09 UTC, idbolshakov requested changes

2021-06-07 17:09 UTC, idbolshakov commented on npm-debug.log
> +0 info it worked if it ends with ok
это тут лишнее

2021-06-23 17:36 UTC, CillianFrost commented
@Saymell => @ idbolshakov

2021-06-23 18:17 UTC, Saymell approved these changes
@idbolshakov

2021-06-23 18:34 UTC, idbolshakov commented
@levushkina

2021-06-24 04:16 UTC, levushkina commented on src/blocks/common/form/form.css
> +  position: absolute;
по-моему, засовывать все элементы формы в один файл - изначально было плохой идеей. 
в итоге, если проекту нужен свой вариант одного элемента, то в проектную директорию придется перетаскивать все

2021-06-24 04:16 UTC, levushkina commented on src/blocks/common/header/header.css
> +.aui-header_m-shade-blue {
если shade-blue - модификатор, то  aui-header_shade-blue

2021-06-24 04:16 UTC, levushkina commented on src/blocks/common/pseudo-select/pseudo-select.css
> +.aui-form-select {
это блок pseudo-select
а у тебя form-select. нужен отдельный файл

2021-06-24 04:16 UTC, levushkina commented on src/blocks/common/related-products/example/common.html
> +<div class="aui-related_products__wrapper">
суть библиотеки - переиспользование
название очень конкретное, в принципе не предполагающее переиспользование
нужно или название переделать или вообще не заносить в библиотеку

2021-06-24 07:51 UTC, CillianFrost commented on src/blocks/common/battery/battery.css
> +  font-family: 'Open Sans';
шрифт со всех элементов убрать, получается?

2021-06-24 07:54 UTC, levushkina commented on src/blocks/common/battery/battery.css
> +  font-family: 'Open Sans';
да

2021-06-24 07:59 UTC, CillianFrost commented on src/blocks/common/related-products/example/common.html
> +<div class="aui-related_products__wrapper">
в теории сопутку могут захотеть вывести в других местах. и батарейка тоже довольно конкретный элемент. я узнаю, может нигде больше не нужна будет, тогда уберу отсюда)

2021-06-24 08:43 UTC, levushkina commented on src/blocks/common/related-products/example/common.html
> +<div class="aui-related_products__wrapper">
у тебя по сути картинка и текст. тут нет ничего специфичного для сопутствующих товаров. это может быть что угодно. название не оправданно.
с батарейкой другая ситуация - врятли такие же стили будут у чего-то другого, кроме батарейки. поэтому название там уместное. но про хранение ее в библиотеке да - надо подумать

2021-06-24 08:50 UTC, CillianFrost commented on src/colors/common.json
> +      "blue": "#028dd8",
меня видимо смутило что этот файл пустой был и я сюда записал. компоненты тоже в папке common создаю. уточню у Вани

2021-06-24 08:58 UTC, levushkina commented on src/colors/common.json
> +      "blue": "#028dd8",
еще мне не понятно, почему цветовая схема пульса тут, а не админки

2021-06-24 09:06 UTC, CillianFrost commented on src/colors/common.json
> +      "blue": "#028dd8",
я цвета с макета брал) если я правильно понял что ты имеешь ввиду

2021-06-24 09:10 UTC, CillianFrost commented on src/blocks/common/form/form.css
> +  position: absolute;
мне тогда весь этот файл на разные разобрать? включая то, что Ксюша писала?

2021-06-25 03:21 UTC, levushkina commented on src/blocks/common/form/form.css
> +  position: absolute;
этот файл в принципе не для  форм админки был создан. а для проектных форм

2021-07-05 08:05 UTC, CillianFrost commented
@levushkina @idbolshakov

2021-07-05 11:42 UTC, levushkina commented on src/blocks/common/admin-select/admin-select.css
> +
строка

2021-07-05 11:42 UTC, levushkina commented on src/blocks/common/admin-text-field/admin-text-field.css
> +.aui-admin-textarea__wrapper {
файл под блок aui-admin-text-field, а описан в нем aui-admin-textarea

2021-07-05 11:42 UTC, levushkina commented on src/blocks/common/header/header.css
> +.aui-header_dark-dark {
у тебя модификаторы то через землю, то через -- 
нужно придерживаться какого-то одного варианта

2021-07-05 11:42 UTC, levushkina commented on src/colors/common.json
> +    "description": "общие цвета, используются на всех порталах",
общие цвета, используются на всех порталах в админке СК

2021-07-05 13:39 UTC, CillianFrost commented
@levushkina up

2021-07-06 03:47 UTC, levushkina commented
пожалуйста, засылай фиксы отдельным коммитом. а то заново приходится 800 строк проверять

2021-07-06 04:11 UTC, levushkina commented on src/blocks/common/admin-related-products/admin-related-products.css
> +.aui-admin-related_products__wrapper {
тут тоже кажется _products должен быть блоком, а не модификатором

2021-07-06 04:11 UTC, levushkina commented on src/blocks/common/link/link.css
> +.aui-link__dotted {
почему это не в admin?

2021-07-06 04:11 UTC, levushkina commented on src/blocks/common/text/example/common.html
> +<div class="aui-text__checkbox-label">
должно быть в admin
мне кажется checkbox-label не должен быть частью text.  это элементов формы, а не текстоввй контент страницы

2021-07-06 08:49 UTC, CillianFrost commented
@levushkina up

2021-07-06 08:57 UTC, levushkina approved these changes

2021-07-06 09:03 UTC, CillianFrost commented
@idbolshakov

2021-07-06 16:45 UTC, idbolshakov requested changes
в общем и целом работа проделана большая и хорошая :+1: 

есть стилистические помарки, которые нужно поправить

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-button-radio/example/common.html
> +  <button class="aui-admin-button-radio__button aui-admin-button-radio__button--active" type="button">Текст</button>
а почему `button-radio` а в разметке `<button type="button" />`  а не `<input type="radio" />` ?

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-calendar-input/admin-calendar-input.css
> +  background-image: url('./calendar-icon.svg');
по бэму картинку надо также назвать как и сущность внутри которой ты ее используешь

в твоем случае `aui-admin-calendar-input.svg`

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-icons/admin-arrow.css
> +.aui-admin-icons__arrow {
файл должен называться `admin-icons__arrow.css`

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
для нейминга элементов блока используем двойное подчеркивание а не двойное тире

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +  background-image: url('./moderation_postpone.svg');
`aui-admin-moderation-button__postpone.svg`

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +  background-image: url('./moderation_decline.svg');
аналогично нейминг

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/moderation_accept.svg
> +<svg width="16" height="12" viewBox="0 0 16 12" fill="none" xmlns="http://www.w3.org/2000/svg">
svg жмем https://jakearchibald.github.io/svgomg/

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/moderation_accept.svg
> +<svg width="16" height="12" viewBox="0 0 16 12" fill="none" xmlns="http://www.w3.org/2000/svg">
и так для всех свг в реквесте

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-rubricator/admin-rubric-block.css
> +.aui-admin-rubric-block__wrapper--solid {
`--` двойные тире не испльзуем

`block-name` - блок
`block-name_dark` - модификатор блока
`block-name__element-name` - элемент
`block-name__element-name_hidde` - модификатор элемента

2021-07-06 16:45 UTC, idbolshakov commented on src/blocks/common/admin-select/admin-select.css
> +  background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTc5MiIgaGVpZ2h0PSIxNzkyIiB2aWV3Qm94PSIwIDAgMTc5MiAxNzkyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIHN0eWxlPSJmaWxsOiM2MTY1NmY
а тут почему инлайн свг? лучше вынести в файл

2021-07-06 16:45 UTC, idbolshakov commented
@levushkina  спасибо за хорошее ревью

2021-07-07 04:45 UTC, levushkina commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
кажется близко и заказы двойное тире используют

2021-07-07 07:31 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
надо будет от этих двойных тире отказаться в пользу единого подхода чтобы не наводить смуты

2021-07-07 13:17 UTC, CillianFrost commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
а двойные тире же по бэму и есть? или мы в этом случае отходит от официальной документации?

2021-07-07 13:29 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
https://ru.bem.info/methodology/quick-start/  в православной версии нет двойных тире

двойные тире этот как один из вариантов нейминга используется.

но мы используем православный вариант

ниже в комментарии я указал как и что там

2021-07-07 13:29 UTC, idbolshakov commented on src/blocks/common/admin-moderation-button/admin-moderation-button.css
> +.aui-admin-moderation-button--postpone {
-- двойные тире не испльзуем

block-name - блок
block-name_dark - модификатор блока
block-name__element-name - элемент
block-name__element-name_hidde - модификатор элемента

дублирую сюда

2021-07-07 18:18 UTC, CillianFrost commented
@idbolshakov up

2021-07-08 07:06 UTC, idbolshakov approved these changes

2021-07-08 07:07 UTC, merged

2021-07-08 07:08 UTC, idbolshakov commented
13.15.0