feature(button-link ПЦ): добавит два стиля для псевдоссылок [skip ci]
abak-press/apress-ui pull request #225
Opened 2021-06-10 10:47 UTC by DanteDeGrave

https://jira.railsc.ru/browse/PC4-26734

2021-06-10 10:47 UTC, DanteDeGrave commented
@idbolshakov @levushkina

2021-06-10 14:29 UTC, idbolshakov requested changes

2021-06-10 14:29 UTC, idbolshakov commented on src/blocks/pulscen/button-link/button-link_dim-red-nohover.css
> +.aui-button-link_dim-red-nohover { color: var(--dim-red); }
а нет ли тут риска того, что кнопке цвет потом поменяют?)
типо будет dim-red, с color: yellow ?)

2021-06-11 05:10 UTC, levushkina commented
> а нет ли тут риска того, что кнопке цвет потом поменяют

риск есть, но если в библиотеке селекторы функционально называть, то их и переиспользовать не получится. кнопки одного и того же цвета/оформления могут использоваться в совершенно разных ситуациях с разными целями. красная ссылка - удаление/предупреждение/ошибка/архив итп. И как ее назвать, чтобы потом во всех кейсах уместно было ее использовать?

ну и по такому принципу практически все в библиотеке именовано. и в коммон и в проектных папках

2021-06-11 05:12 UTC, idbolshakov commented
кароче мне такая история не очень нравится, но если пока нет понимания как это поправить и вам с этим ок, то ок

2021-06-11 05:12 UTC, idbolshakov approved these changes

2021-06-11 05:16 UTC, DanteDeGrave commented
> кароче мне такая история не очень нравится, но если пока нет понимания как это поправить и вам с этим ок, то ок

Так может имеет смысл данный вопрос обсудить на общем созвоне или в чате или еще как, так как библиотека общая. Продумать концепт, взоможные исключения (без них никак) и начать следовать только ему.

2021-06-11 05:30 UTC, idbolshakov commented
> Так может имеет смысл данный вопрос обсудить на общем созвоне или в чате или еще как, так как библиотека общая. Продумать концепт\критерий, взоможные исключения (без них никак) и начать следовать только ему.

идея хорошая)

можешь проработать чуть чуть вопрос и поднять эту тему на общем созвоне)

2021-06-11 05:44 UTC, idbolshakov commented
13.3.0

2021-06-11 05:44 UTC, merged