fix: remove ES6 functions from istorage
abak-press/apress-ui pull request #229
Opened 2021-06-15 15:48 UTC by KonstantinBel

[PATCH] в старых версиях хрома не доступны forEach и append, заменяем их на for и appendChild
https://jira.railsc.ru/browse/BPC-18918

2021-06-15 15:49 UTC, KonstantinBel commented
@Nats92 -> idbolshakov

2021-06-16 02:19 UTC, Nats92 commented on src/blocks/common/istorage/istorage.js
> +          console.log('_sendMessageOnIframeLoad', i)
Это нужно?

2021-06-16 02:20 UTC, Nats92 commented
@idbolshakov

2021-06-16 05:01 UTC, idbolshakov requested changes

2021-06-16 05:01 UTC, idbolshakov commented on src/blocks/common/istorage/istorage.js
> +          console.log('_sendMessageOnIframeLoad', i)
вроде не нужно

2021-06-16 06:34 UTC, KonstantinBel commented on src/blocks/common/istorage/istorage.js
> +          console.log('_sendMessageOnIframeLoad', i)
fixed

2021-06-16 06:41 UTC, Nats92 approved these changes

2021-06-16 06:43 UTC, Nats92 commented
только не поняла я почему бабель не обработал это как следует. Тут же получается, что если бабель обрабатывает новый код так, что он не поддерживается в старом хроме, то у нас остальной код в es6 тоже не будет работать

2021-06-16 06:47 UTC, KonstantinBel commented
> только не поняла я почему бабель не обработал это как следует. Тут же получается, что если бабель обрабатывает новый код так, что он не поддерживается в старом хроме, то у нас остальной код в es6 тоже не будет работать. Надо разобраться с этой темой.

просто этот же код сейчас в apress-application, и там нет бабеля, я исправил там, и просто скопировал сюда, но в общемт то тут это действительно не нужно, проверил билд, там нет es6 функций

2021-06-16 06:48 UTC, Nats92 commented
можеттогда и не стоит мержить?)

2021-06-16 06:49 UTC, KonstantinBel commented
думаю не стоит, все равно же когданибудь избавимся от версии из apress-application

2021-06-16 06:49 UTC, closed without merging