feature(social-networks): add new bem-block
abak-press/apress-ui pull request #231
Opened 2021-06-16 11:20 UTC by FonDumik

[MINOR] Добавит блок соц.сетей из макета по редизайну портала

https://jira.railsc.ru/browse/SG-7149

2021-06-16 11:21 UTC, FonDumik commented
@idbolshakov 
@VeraVLVlas

2021-06-16 11:34 UTC, idbolshakov commented
коммит мессадж совсем неправильный

`feature(lookmart): add social-networks block` должно быть что-то такое

2021-06-16 11:37 UTC, FonDumik commented
> коммит мессадж совсем неправильный
> 
> `feature(lookmart): add social-networks block` должно быть что-то такое

именно сообщение коммита или название ПРа?

2021-06-16 11:46 UTC, idbolshakov commented
> именно сообщение коммита или название ПРа?

и то и то

2021-06-16 11:53 UTC, FonDumik commented
> > именно сообщение коммита или название ПРа?
> 
> и то и то

готово

2021-06-16 12:11 UTC, idbolshakov requested changes

2021-06-16 12:11 UTC, idbolshakov commented on src/blocks/lookmart/social-networks/example/small.html
> +    <span class="social-networks__item fb" data-ga-action="FB" data-to="https://www.facebook.com/yapokupayuru" target="_blank"></span>
что за класс `fb` и ниже `vk`, `instagram` и тд и тп?

внутри БЭМ блока должны быть стили только по БЭМ нотации

2021-06-17 04:53 UTC, FonDumik commented
@idbolshakov

2021-06-17 08:00 UTC, idbolshakov requested changes

2021-06-17 08:00 UTC, idbolshakov commented on src/blocks/lookmart/social-networks_old/social-networks_old.css
> +.social-networks_old .social-networks {
это не отдельный блок а модификатор блока `social-networks` поэтому все это нужно положить в папку `src/blocks/lookmart/social-networks`

2021-06-17 10:19 UTC, FonDumik commented
@idbolshakov

2021-06-17 11:42 UTC, idbolshakov approved these changes

2021-06-17 11:43 UTC, merged

2021-06-17 11:44 UTC, idbolshakov commented
13.8.0