fix(lookmart): fix social-networks block alignment
abak-press/apress-ui pull request #240
Opened 2021-06-21 07:21 UTC by FonDumik

[MINOR] исправит выравнивание блоков соц.сетей

https://jira.railsc.ru/browse/SG-7149

2021-06-21 07:22 UTC, FonDumik commented
@idbolshakov 
@VeraVLVlas

2021-06-21 19:55 UTC, idbolshakov requested changes

2021-06-21 19:55 UTC, idbolshakov commented on src/blocks/lookmart/social-networks/social-networks_old.css
> +  width: fit-content;
вот без этого свойства можно? у него поддержка в браузерах не очень хорошая

2021-06-22 04:19 UTC, FonDumik commented on src/blocks/lookmart/social-networks/social-networks_old.css
> +  width: fit-content;
Исправил

2021-06-22 04:19 UTC, FonDumik commented
@idbolshakov

2021-06-22 05:46 UTC, idbolshakov requested changes

2021-06-22 05:46 UTC, idbolshakov commented on src/blocks/lookmart/social-networks/social-networks_old.css
> +  width: min-content;
![image](https://user-images.githubusercontent.com/17525238/122870422-172e9680-d347-11eb-80c3-36a5698d9b77.png)
тут еще хуже поддержка

давай или `auto` или проценты

2021-06-22 05:48 UTC, FonDumik commented on src/blocks/lookmart/social-networks/social-networks_old.css
> +  width: min-content;
Почему flex-basis?
![image](https://user-images.githubusercontent.com/46936826/122870635-5bba3200-d347-11eb-9648-79cbe5ab5f95.png)

2021-06-22 06:20 UTC, idbolshakov approved these changes

2021-06-22 06:20 UTC, merged

2021-06-22 06:21 UTC, idbolshakov commented
13.8.2