add blizko scroll and fix aui-list
abak-press/apress-ui pull request #260
Opened 2021-07-09 12:17 UTC by Nats92

fix: add transparent borders to .aui-list__item to prevent jumping on select
[MINOR]: Добавит скролл для Близко
[PATCH]: Добавит невидимые границы к .aui-list__item чтобы избежать подпрыгивания при выборе пункта
https://jira.railsc.ru/browse/BPC-18981

2021-07-09 12:18 UTC, Nats92 commented
@idbolshakov

2021-07-12 08:18 UTC, idbolshakov requested changes
я в выходные думал про эту проблему и у меня возникла мысль как чуть чуть улучшить эту историю

что если мы сделаем класс `scroll`, который будет вешаться на какой-то контейнер, в твоем случае подойдет тег `body` а в других случаях можно более маленькую область задать. Тогда будет все более инкапуслировано.

вот примерно так стили будут:

```
.scroll {
  --scrollbar-color: yellow;

}

.scroll * {
  scrollbar-width: thin;
  ....
}
```

?

2021-07-12 08:53 UTC, Nats92 commented
> я в выходные думал про эту проблему и у меня возникла мысль как чуть чуть улучшить эту историю
> 
> что если мы сделаем класс `scroll`, который будет вешаться на какой-то контейнер, в твоем случае подойдет тег `body` а в других случаях можно более маленькую область задать. Тогда будет все более инкапуслировано.
> 
> вот примерно так стили будут:
> 
> ```
> .scroll {
>   --scrollbar-color: yellow;
> 
> }
> 
> .scroll * {
>   scrollbar-width: thin;
>   ....
> }
> ```
> 
> ?

да, можно. Сейчас переделаю

2021-07-12 09:16 UTC, Nats92 commented
:up: 
поправила скролл и еще модификатор дослала для элемента списка.

2021-07-12 11:41 UTC, idbolshakov approved these changes

2021-07-12 11:42 UTC, merged

2021-07-12 11:50 UTC, idbolshakov commented
13.16.0