feat: add battery and battery popup components
abak-press/apress-ui pull request #296
Opened 2021-08-16 07:30 UTC by CillianFrost

https://jira.railsc.ru/browse/GOODS-2892

2021-08-16 07:30 UTC, CillianFrost commented
@Saymell => @ idbolshakov

2021-08-16 07:40 UTC, Saymell commented on src/blocks/common/admin-battery-popup/example/common.html
> +            <b>
Насколько знаю, если нет семантической причины использовать элемент `<b>`,  то лучше использовать css свойство `font-weight` со значением `bold` для изменения толщины текста. Но в целом думаю не критично, количество строк правда растет из-за лишнего тега.

2021-08-16 07:40 UTC, Saymell approved these changes
@idbolshakov

2021-08-16 07:53 UTC, idbolshakov requested changes

2021-08-16 07:53 UTC, idbolshakov commented on src/blocks/common/admin-battery-popup/admin-battery-popup.css
> +.aui-admin-battery-popup__content__description__list {
это вообще че за селекторы такие?))

2021-08-16 11:39 UTC, CillianFrost commented on src/blocks/common/admin-battery-popup/example/common.html
> +            <b>
поправлю. там изначально не нужен был класс и отдельный блок, но в итоге стал нужен. так что бешки можно убрать. делал по аналогии с существующей батарейкой.

2021-08-16 11:41 UTC, CillianFrost commented on src/blocks/common/admin-battery-popup/admin-battery-popup.css
> +.aui-admin-battery-popup__content__description__list {
хотел как раз спросить) если у меня высокий уровень вложенности, в котором ещё много довольно одинаковых логических блоков, но с разной вёрсткой, то мне какой структуры придерживаться? `block__element__element__element` или `block__element` независимо от уровня вложенности?

2021-08-16 12:27 UTC, idbolshakov commented on src/blocks/common/admin-battery-popup/admin-battery-popup.css
> +.aui-admin-battery-popup__content__description__list {
`block__element` в БЭМ нет элемента-элемента, есть только элемент блока

2021-08-17 05:47 UTC, idbolshakov approved these changes

2021-08-17 05:47 UTC, merged

2021-08-17 05:48 UTC, idbolshakov commented
14.3.0