feature: add blizko button without round
abak-press/apress-ui pull request #330
Opened 2021-09-13 05:58 UTC by Comediant24

https://jira.railsc.ru/browse/BPC-19372

2021-09-13 05:59 UTC, Comediant24 commented
@KonstantinBel

2021-09-13 06:41 UTC, KonstantinBel approved these changes

2021-09-13 07:05 UTC, Comediant24 commented
@idbolshakov

2021-09-13 08:47 UTC, idbolshakov requested changes

2021-09-13 08:47 UTC, idbolshakov commented on src/blocks/blizko/button/button_round.css
> +.aui-button_round_false {
че-то не пойму)

как-то запутанно)

если тебе нужен модификатор "без закругления" то и назови его `.aui-button_without-round` 

а  то как-то сложно получается

2021-09-13 09:20 UTC, Comediant24 commented on src/blocks/blizko/button/button_round.css
> +.aui-button_round_false {
https://github.com/abak-press/apress-ui/pull/330/files#diff-f26816702df023182ab3a73ab1294762be54cb262996b01218aa4933109e31dcR1-R3

2021-09-14 16:53 UTC, idbolshakov requested changes

2021-09-14 16:53 UTC, idbolshakov commented on src/blocks/blizko/button/button_round.css
> +.aui-button__without-round {
так, а почему теперь `__without-roud` стал элементом блок `aui-button`?) это же модификатор. Должно быть  `aui-button_without-round`

2021-09-15 08:28 UTC, Comediant24 commented on src/blocks/blizko/button/button_round.css
> +.aui-button__without-round {
О, блин. Неправильно find & replace сделал.(

2021-09-15 11:01 UTC, idbolshakov approved these changes

2021-09-15 11:01 UTC, merged

2021-09-15 11:14 UTC, idbolshakov commented
14.11.0