feature(pulscen): add message & cs-buttons, change links hover
abak-press/apress-ui pull request #355
Opened 2021-11-11 10:43 UTC by levushkina

[MINOR]: добавит для пульсцен кнопки и сообщения, изменит стили ссылок

https://jira.railsc.ru/browse/PC4-27394

2021-11-11 10:44 UTC, levushkina commented
@Comediant24 => @ idbolshakov

2021-11-11 12:32 UTC, Comediant24 reviewed
`src/blocks/pulscen/cs-message/index.js` пустой.

2021-11-11 12:32 UTC, Comediant24 commented on src/blocks/pulscen/cs-button/button_company-site-big.css
> +.aui-button_company-site-big {
Тут разве больше не походит модификатор типа ключ_значение?
https://ru.bem.info/methodology/quick-start/#ключ-значение

2021-11-12 03:34 UTC, levushkina commented on src/blocks/pulscen/cs-button/button_company-site-big.css
> +.aui-button_company-site-big {
нет, потому что есть модификатор без значения

2021-11-12 03:34 UTC, levushkina commented
@idbolshakov

2021-11-12 05:19 UTC, idbolshakov requested changes

2021-11-12 05:19 UTC, idbolshakov commented on src/blocks/pulscen/cs-button/button_company-site-medium.css
> +.aui-button_company-site-medium {
я вот заметил косяк. Но видимо это до тебя еще было. Папка называется `cs-button`. А сам компонент `aui-button`

по идее должно быть `aui-cs-button`. Иначе возникает конфликт с обычной кнопкой `aui-button`. 

Есть возможно просто и быстро поменять этот нейминг?

2021-11-12 05:19 UTC, idbolshakov commented on src/blocks/pulscen/cs-message/cs-message.css
> +.aui-cs-message {
а вот тут как раз с `cs-` префиксом

2021-11-12 05:43 UTC, levushkina commented on src/blocks/pulscen/cs-button/button_company-site-medium.css
> +.aui-button_company-site-medium {
> я вот заметил косяк

я тоже. но быстро не поменяешь, поэтому оставила
по сути создали не новую кнопку, а "как-бы" модификатор aui-button. поскольку меня не было на встрече, где вы эти кнопки обсуждали, я не поняла задумки. хотела с стобой потом отдельно обсудить

2021-11-12 05:46 UTC, levushkina commented on src/blocks/pulscen/cs-button/button_company-site-medium.css
> +.aui-button_company-site-medium {
если что - заведем отдельную задачу, по приборке кнопок

2021-11-12 06:00 UTC, idbolshakov commented on src/blocks/pulscen/cs-button/button_company-site-medium.css
> +.aui-button_company-site-medium {
отлично, давайте обязательно заведем задачу

2021-11-12 06:00 UTC, idbolshakov approved these changes

2021-11-12 06:00 UTC, merged

2021-11-12 06:00 UTC, idbolshakov commented
14.18.0