feature(pulscen\app-button): add wide button
abak-press/apress-ui pull request #510
Opened 2022-11-02 10:58 UTC by woklisgm

[MINOR]: add wide button in pulscen\app-button

https://jira.railsc.ru/browse/PC4-28877

2022-11-02 11:03 UTC, woklisgm commented on src/blocks/common/app-button/app-button.css
> +  background-color: transparent !important;
Объясню почему добавил important )
![image](https://user-images.githubusercontent.com/23363843/199473014-374698d5-7c1b-459a-ae70-f002b89fb582.png)
Есть две кнопки. У гугл-плэй иконка и текст разделены на две части. Иконка в after, текст в before.
У апп-сторе нужно было сделать так же. Но когда у апп стор нужно задавать бэкграунд для маски в after чтобы яблоко менял цвет. Но в гугл-плэй иконка через background поэтому когда задаем background-color фон под иконкой заливается. Чтобы такого не было, сделал так. Думаю что это ни где не нужно будет переопределять поэтому не сильно критично.

2022-11-02 11:05 UTC, woklisgm commented
@Comediant24 => @ DanteDeGrave

2022-11-02 11:15 UTC, Comediant24 commented on src/blocks/common/app-button/app-button.css
> +  background-color: transparent !important;
А где в ТЗ про цвет?

2022-11-02 12:31 UTC, woklisgm commented on src/blocks/common/app-button/app-button.css
> +  background-color: transparent !important;
![image](https://user-images.githubusercontent.com/23363843/199489817-1a16eefe-3b22-4a7b-9fa2-84120d314063.png)
Цвет может меняться в зависимости от модификатора

2022-11-02 14:36 UTC, Comediant24 commented on src/blocks/common/app-button/app-button.css
> +  background-color: transparent !important;
У модификатора тоже может быть модификатор.)
Можно сделать `aui-app-button_app-store_black`

2022-11-02 14:41 UTC, Comediant24 requested changes

2022-11-02 14:41 UTC, Comediant24 commented on src/blocks/pulscen/app-button/example/common.html
> +</div>
И `aui-app-button_small` ограничь в ширине в библиотеке для наглядности. А то смотреться будут одинаково с плашками выше.

2022-11-07 12:32 UTC, woklisgm commented on src/blocks/common/app-button/app-button.css
> +  background-color: transparent !important;
упс, изначально не там правки сделал ) все переписал заново поэтому сделал push force

2022-11-07 13:28 UTC, Comediant24 approved these changes
@DanteDeGrave

2022-11-08 07:13 UTC, DanteDeGrave approved these changes
Вроде и норм, но лично я бы разделил все таки логотипы на разные ксс подули, в демо пусть будут на одной странице. Просто вдруг одна из компаний сменит логотип или еще чего, а тут не так гибко. Так что прими решение сам.

2022-11-08 10:42 UTC, merged

2022-11-08 10:44 UTC, Comediant24 commented
14.61.0