feature(common): add cross icon & link style without bold
abak-press/apress-ui pull request #513
Opened 2022-11-03 18:25 UTC by BalmasovAS

[MINOR] Добавит иконку "крестик" и стиль ссылки "не жирный" для страницы создания товара. https://jira.railsc.ru/browse/GOODS-3248

2022-11-07 06:04 UTC, BalmasovAS commented
@DanteDeGrave => @ Comediant24

2022-11-07 06:11 UTC, Comediant24 requested changes

2022-11-07 06:11 UTC, Comediant24 commented on src/blocks/common/admin-link/admin-link__no-bold.css
> +.aui-admin-link__no-bold {
Нейминг не самый удачный. Плюс ты используешь эту сущность, как модификатор, а пишешь, как элемент.

2022-11-07 06:22 UTC, DanteDeGrave commented on src/blocks/common/admin-link/admin-link__no-bold.css
> +.aui-admin-link__no-bold {
Да, подобная практика черевата тем, что мы по тихоньку превратим библиотеку в бутстрап и придется делать еще большее дробление рубрик, так как что бы загрузить один стиль, ты будешь тащить кучу не нужных на страницу из этой рубрики.

2022-11-08 14:36 UTC, DanteDeGrave approved these changes
@Comediant24

2022-11-08 14:36 UTC, DanteDeGrave commented on src/blocks/common/admin-icons/admin-icons__cross.css
> +  top: 3px;
я бы сделал лево и верх 50%, а транслейт( -50%, -50%). Что бы не зависимо от области клика (контейнер креста), он всегда был в центре (просто у нас недавно заказчики задумались об увеличении области кликов подобных кнопок и подобный подход дал возможность легко манипулировать шириной и высотой контейнера). И еще перед псевдо-элементами :: , одно двоеточие у псевдо-классов. Ну это чисто договоренность :)

2022-11-09 06:56 UTC, DanteDeGrave approved these changes

2022-11-09 06:57 UTC, Comediant24 approved these changes

2022-11-09 12:32 UTC, merged

2022-11-09 12:33 UTC, Comediant24 commented
14.63.0