feature(fonts lookmart): added Oranienbaum fonts woff2 and woff [skip ci]
abak-press/apress-ui pull request #657
Opened 2024-07-03 09:32 UTC by iskra13

https://jira.railsc.ru/browse/SG-8739

2024-07-03 09:35 UTC, iskra13 commented
Скачалась это:
![image](https://github.com/abak-press/apress-ui/assets/96988385/2aa71738-1b57-463f-8697-d06eb5c73df3)

![image](https://github.com/abak-press/apress-ui/assets/96988385/11126c1d-fd92-458b-a72c-3f71c7869330)

после чего конвертнул их в woff woff2:
![image](https://github.com/abak-press/apress-ui/assets/96988385/48922bf6-da57-4fcf-b6b8-644274a498e0)

2024-07-03 09:35 UTC, iskra13 commented
@Comediant24, посмотри нормально ли

2024-07-03 09:46 UTC, iskra13 commented
чет кажется они не похожи

![image](https://github.com/abak-press/apress-ui/assets/96988385/73cbd584-4cc7-4410-bf55-ea90f0750863)
![image](https://github.com/abak-press/apress-ui/assets/96988385/f44ea77a-d58b-47c7-9b12-caf6cb90154f)

2024-07-03 11:16 UTC, iskra13 commented
Я на глаз начал присматриватся и чет непонятно(

2024-07-04 04:35 UTC, Comediant24 commented
Мне тоже кажется что не похоже) Может на других источниках поискать?

2024-07-04 06:44 UTC, iskra13 commented
@Comediant24, шесть источников перепробовал, все в превью не так выглядят, делаю тоже самое на винде везде нормально все, давай попробуем смержить? и я посмотрю как будет, ну я все перепробовал, они долджны быть нормальными

2024-07-04 06:51 UTC, iskra13 commented
Загрузил эти сконвертированные woff & woff2 на онлайн предосмотрел, показал что они нормальные....
![image](https://github.com/abak-press/apress-ui/assets/96988385/4d4d751d-379f-41b2-b4a2-b2bc8e606171)

2024-07-04 07:01 UTC, Comediant24 requested changes

2024-07-04 07:01 UTC, Comediant24 commented on src/blocks/lookmart/fonts/fonts.css
> +  font-style: normal;
Давай добавим font-display: swap;

2024-07-04 07:11 UTC, iskra13 commented
@Comediant24, добавли

2024-07-04 07:22 UTC, Comediant24 approved these changes

2024-07-04 07:22 UTC, merged

2024-07-04 07:28 UTC, Comediant24 commented
@iskra13 [14.106.0](https://github.com/abak-press/apress-ui/pull/658)