feat(portal): change style recent products block
abak-press/apress-ui pull request #659
Opened 2024-07-05 09:02 UTC by ovsyanik-ka

https://jira.railsc.ru/browse/BPC-23612
[PATCH]: перенесет стили recent-products, offer-root and discount-products из проекта

2024-07-05 09:02 UTC, ovsyanik-ka commented
@Artyom774 -> @Comediant24

2024-07-05 09:10 UTC, Artyom774 approved these changes

2024-07-05 10:37 UTC, Comediant24 commented
Я еще добавлю замечаний, а пока добавь пожалуйста мок html  для этих элементов

2024-07-08 04:06 UTC, ovsyanik-ka commented on src/blocks/blizko/recent-products/example/index.html
> +      <p class="product-price__container">
в этом блоке могут быть разные типы цен
от/до
цена договорная
со скидкой и тд

надо ли все прописывать?

2024-07-08 05:32 UTC, Comediant24 commented on src/blocks/blizko/offer-root-card/offer-root-card.css
> +  height: 100%;
Тут бы тоже text-decoration: none

2024-07-08 05:55 UTC, Comediant24 requested changes
- У тебя должно получиться всего два новых элемента вместо трех
![image](https://github.com/abak-press/apress-ui/assets/63135211/460d8607-0fa3-4597-925f-4c2613d79c73)
- discount-products и recent-products - это один и тот же элемент ui. Нет нужды их разбивать. Назвать стоит как то универсальнее, чтобы не ограничивать именем блока область применения данного ui элемента (recent, discount-products - из названия накладывают ограниченные места применения). Я бы назвал product-short-card
- Тоже самое с offer-root-card - в имени ограничение. offer-short-card

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/offer-root-card/offer-root-card.css
> +}
Тут бы тоже text-decoration: none

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/discount-products/discount-products.css
> +}
И тут

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/recent-products/recent-products.css
> +.aui-recent-products__link_title {
Тут долно быть aui-recent-products__link-title, наверное

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/recent-products/example/index.html
В этом блоке сделаны две ссылки. В твоем ПР в проекте тоже на этом блоке две ссылки. Но тут можно сделать одну ссылку, по аналогии с блоком Огромные скидки на главной

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/recent-products/example/index.html
> +  <a class="aui-recent-products__link_image" href="#">
Тут тоже наверное имелось ввиду aui-recent-products__link-image

2024-07-08 05:55 UTC, Comediant24 commented on src/blocks/blizko/recent-products/recent-products.css
> +  gap: 10px;
У блока высота 90px и еще gap есть 10px
У элемента aui-recent-products__link_title входящего в него высота 72px
Получается что для цены остается 8px - но font-size у блока цены 16px)

2024-07-08 05:57 UTC, Comediant24 commented on src/blocks/blizko/recent-products/example/index.html
> +      <p class="product-price__container">
Не нужно. Это уже граница другого блока)

2024-07-09 11:38 UTC, ovsyanik-ka commented
@Comediant24

2024-07-10 04:10 UTC, Comediant24 requested changes

2024-07-10 04:10 UTC, Comediant24 commented on src/blocks/blizko/product-short-card/example/index.html
> +    background-color: var(--green-d202);
Вот эти стили тут не нужны. Они из библиотеки подтянутся

2024-07-10 05:27 UTC, Comediant24 requested changes

2024-07-10 05:27 UTC, Comediant24 commented on src/blocks/blizko/product-short-card/product-short-card.css
> +  margin-bottom: 0;
Модификаторы нужно располагать под модифицируемым элементом

2024-07-10 05:38 UTC, ovsyanik-ka commented
@Comediant24

2024-07-10 05:43 UTC, Comediant24 approved these changes

2024-07-10 05:46 UTC, ovsyanik-ka commented
@Comediant24 
merge

2024-07-10 05:47 UTC, merged

2024-07-10 05:49 UTC, Comediant24 commented
[14.107.0](https://github.com/abak-press/apress-ui/pull/660)